/*
 * This file is generated by jOOQ.
 */
package com.example.banksystem.database.schema;


import com.example.banksystem.database.schema.tables.BankInfo;
import com.example.banksystem.database.schema.tables.UserInfo;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in bank_db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index BANK_INFO_BANK_ID = Internal.createIndex(DSL.name("bank_id"), BankInfo.BANK_INFO, new OrderField[] { BankInfo.BANK_INFO.BANK_ID }, false);
    public static final Index USER_INFO_BANK_ID = Internal.createIndex(DSL.name("bank_id"), UserInfo.USER_INFO, new OrderField[] { UserInfo.USER_INFO.BANK_ID }, false);
    public static final Index USER_INFO_USER_ID = Internal.createIndex(DSL.name("user_id"), UserInfo.USER_INFO, new OrderField[] { UserInfo.USER_INFO.USER_ID }, false);
}
