/*
 * This file is generated by jOOQ.
 */
package com.example.banksystem.database.schema.tables.records;


import com.example.banksystem.database.schema.tables.UserInfo;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserInfoRecord extends UpdatableRecordImpl<UserInfoRecord> implements Record6<Integer, Integer, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>bank_db.user_info.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>bank_db.user_info.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bank_db.user_info.bank_id</code>.
     */
    public void setBankId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>bank_db.user_info.bank_id</code>.
     */
    public Integer getBankId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>bank_db.user_info.sum</code>.
     */
    public void setSum(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>bank_db.user_info.sum</code>.
     */
    public Integer getSum() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>bank_db.user_info.term</code>.
     */
    public void setTerm(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>bank_db.user_info.term</code>.
     */
    public Integer getTerm() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>bank_db.user_info.loan</code>.
     */
    public void setLoan(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>bank_db.user_info.loan</code>.
     */
    public Integer getLoan() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>bank_db.user_info.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>bank_db.user_info.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Integer, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return UserInfo.USER_INFO.ID;
    }

    @Override
    public Field<Integer> field2() {
        return UserInfo.USER_INFO.BANK_ID;
    }

    @Override
    public Field<Integer> field3() {
        return UserInfo.USER_INFO.SUM;
    }

    @Override
    public Field<Integer> field4() {
        return UserInfo.USER_INFO.TERM;
    }

    @Override
    public Field<Integer> field5() {
        return UserInfo.USER_INFO.LOAN;
    }

    @Override
    public Field<Integer> field6() {
        return UserInfo.USER_INFO.USER_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getBankId();
    }

    @Override
    public Integer component3() {
        return getSum();
    }

    @Override
    public Integer component4() {
        return getTerm();
    }

    @Override
    public Integer component5() {
        return getLoan();
    }

    @Override
    public Integer component6() {
        return getUserId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getBankId();
    }

    @Override
    public Integer value3() {
        return getSum();
    }

    @Override
    public Integer value4() {
        return getTerm();
    }

    @Override
    public Integer value5() {
        return getLoan();
    }

    @Override
    public Integer value6() {
        return getUserId();
    }

    @Override
    public UserInfoRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public UserInfoRecord value2(Integer value) {
        setBankId(value);
        return this;
    }

    @Override
    public UserInfoRecord value3(Integer value) {
        setSum(value);
        return this;
    }

    @Override
    public UserInfoRecord value4(Integer value) {
        setTerm(value);
        return this;
    }

    @Override
    public UserInfoRecord value5(Integer value) {
        setLoan(value);
        return this;
    }

    @Override
    public UserInfoRecord value6(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserInfoRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserInfoRecord
     */
    public UserInfoRecord() {
        super(UserInfo.USER_INFO);
    }

    /**
     * Create a detached, initialised UserInfoRecord
     */
    public UserInfoRecord(Integer id, Integer bankId, Integer sum, Integer term, Integer loan, Integer userId) {
        super(UserInfo.USER_INFO);

        setId(id);
        setBankId(bankId);
        setSum(sum);
        setTerm(term);
        setLoan(loan);
        setUserId(userId);
    }
}
