/*
 * This file is generated by jOOQ.
 */
package com.example.banksystem.database.schema.tables;


import com.example.banksystem.database.schema.BankDb;
import com.example.banksystem.database.schema.Indexes;
import com.example.banksystem.database.schema.Keys;
import com.example.banksystem.database.schema.tables.records.UserInfoRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserInfo extends TableImpl<UserInfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>bank_db.user_info</code>
     */
    public static final UserInfo USER_INFO = new UserInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserInfoRecord> getRecordType() {
        return UserInfoRecord.class;
    }

    /**
     * The column <code>bank_db.user_info.id</code>.
     */
    public final TableField<UserInfoRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>bank_db.user_info.bank_id</code>.
     */
    public final TableField<UserInfoRecord, Integer> BANK_ID = createField(DSL.name("bank_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>bank_db.user_info.sum</code>.
     */
    public final TableField<UserInfoRecord, Integer> SUM = createField(DSL.name("sum"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>bank_db.user_info.term</code>.
     */
    public final TableField<UserInfoRecord, Integer> TERM = createField(DSL.name("term"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>bank_db.user_info.loan</code>.
     */
    public final TableField<UserInfoRecord, Integer> LOAN = createField(DSL.name("loan"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>bank_db.user_info.user_id</code>.
     */
    public final TableField<UserInfoRecord, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private UserInfo(Name alias, Table<UserInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserInfo(Name alias, Table<UserInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>bank_db.user_info</code> table reference
     */
    public UserInfo(String alias) {
        this(DSL.name(alias), USER_INFO);
    }

    /**
     * Create an aliased <code>bank_db.user_info</code> table reference
     */
    public UserInfo(Name alias) {
        this(alias, USER_INFO);
    }

    /**
     * Create a <code>bank_db.user_info</code> table reference
     */
    public UserInfo() {
        this(DSL.name("user_info"), null);
    }

    public <O extends Record> UserInfo(Table<O> child, ForeignKey<O, UserInfoRecord> key) {
        super(child, key, USER_INFO);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : BankDb.BANK_DB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.USER_INFO_BANK_ID, Indexes.USER_INFO_USER_ID);
    }

    @Override
    public Identity<UserInfoRecord, Integer> getIdentity() {
        return (Identity<UserInfoRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<UserInfoRecord> getPrimaryKey() {
        return Keys.KEY_USER_INFO_PRIMARY;
    }

    @Override
    public List<ForeignKey<UserInfoRecord, ?>> getReferences() {
        return Arrays.asList(Keys.USER_INFO_IBFK_1, Keys.USER_INFO_IBFK_2);
    }

    private transient BankType _bankType;
    private transient User _user;

    public BankType bankType() {
        if (_bankType == null)
            _bankType = new BankType(this, Keys.USER_INFO_IBFK_1);

        return _bankType;
    }

    public User user() {
        if (_user == null)
            _user = new User(this, Keys.USER_INFO_IBFK_2);

        return _user;
    }

    @Override
    public UserInfo as(String alias) {
        return new UserInfo(DSL.name(alias), this);
    }

    @Override
    public UserInfo as(Name alias) {
        return new UserInfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserInfo rename(String name) {
        return new UserInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserInfo rename(Name name) {
        return new UserInfo(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
